### ISSUE TITLE
cv2.error: OpenCV(3.4.2) 

### ISSUE THREAD

**Issue by onthway** [whitelok/watermark-remover#15]
```
2019-06-11 11:54:52 mp-hr autowatermarkremoval.solver[16582] INFO Computing gradients
2019-06-11 11:55:17 mp-hr autowatermarkremoval.solver[16582] INFO Computing median gradients.
2019-06-11 12:03:51 mp-hr autowatermarkremoval.utils[16582] DEBUG saving obj result/Wm_gradx_1689_3000_3
2019-06-11 12:03:53 mp-hr autowatermarkremoval.utils[16582] DEBUG saving obj result/Wm_grady_1689_3000_3
2019-06-11 12:03:55 mp-hr autowatermarkremoval.solver[16582] DEBUG The position of watermark gardient is in (-2, 1624, -3, 3002)
2019-06-11 12:03:55 mp-hr autowatermarkremoval.utils[16582] DEBUG saving obj result/Wm_gradx_cropped_0_3_3
2019-06-11 12:03:55 mp-hr autowatermarkremoval.utils[16582] DEBUG saving obj result/Wm_grady_cropped_0_3_3
Traceback (most recent call last):
  File "./main.py", line 64, in <module>
  File "./autowatermarkremoval/solver.py", line 539, in solve
  File "./autowatermarkremoval/solver.py", line 425, in solve
  File "./autowatermarkremoval/solver.py", line 301, in _possion_reconstruct
cv2.error: OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/imgproc/src/filter.cpp:288: error: (-215:Assertion failed) wholeSize.width > 0 && wholeSize.height > 0 in function 'proceed'
```
The above is debug info.

My sample dataset has email you.

**Comment by whitelok** [comment]
DEBUG The position of watermark gardient is in (-2, 1624, -3, 3002)
seems your watermark detection result is too large to calculate
or you can reduce the factor while doing training

**Comment by whitelok** [comment]
will open again when meet this issue
