### ISSUE TITLE
Get caught in loop with train.sh

### ISSUE THREAD

**Issue by dlwalter** [whitelok/watermark-remover#21]
When I run ./train.sh I get a figure 1 with 7 different method results (TM_CCOEFF, ...etc) When I close that window I get a python debug prompt (Pdb) and if I type continue it asks me to select a method result.  

Then I get a new figure with the watermark, then it blacks out and I get a warning "invalid value encountered in true_divide.

```
> /Users/me/Workspace/Sandbox/watermark-remover/autowatermarkremoval/solver.py(241)_detect_watermark()
(Pdb) continue
Please select a method result
1. cv2.TM_CCOEFF
2. cv2.TM_CCOEFF_NORMED
3. cv2.TM_CCORR
4. cv2.TM_CCORR_NORMED
5. cv2.TM_SQDIFF
6. cv2.TM_SQDIFF_NORMED
7. CANNY_2D_FILTER
:1
2019-10-11 15:14:06 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:06 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:06 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:18 dlw.flightwave.aero autowatermarkremoval.utils[92544] DEBUG get_cropped_image min_x=120, min_y=302, max_x=395, max_y=407
Traceback (most recent call last):
  File "./autowatermarkremoval/solver.py", line 414, in solve
ValueError: could not broadcast input array from shape (275,105,3) into shape (105,275,3)
/Users/me/Workspace/Sandbox/watermark-remover/.direnv/python-3.6.5/lib/python3.6/site-packages/matplotlib/figure.py:98: MatplotlibDeprecationWarning:
Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  "Adding an axes using the same arguments as a previous axes "
/Users/me/Workspace/Sandbox/watermark-remover/autowatermarkremoval/utils.py:87: RuntimeWarning: invalid value encountered in true_divide
2019-10-11 15:14:18 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCOEFF (100, 288) (375, 393)
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCOEFF_NORMED (100, 288) (375, 393)
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCORR (425, 395) (700, 500)
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCORR_NORMED (425, 43) (700, 148)
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_SQDIFF (110, 309) (385, 414)
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_SQDIFF_NORMED (0, 0) (275, 105)
2019-10-11 15:14:30 me.me.com autowatermarkremoval.solver[92544] DEBUG CANNY_2D_FILTER (154, 314) (429, 419)
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:14:30 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
> /Users/me/Workspace/Sandbox/watermark-remover/autowatermarkremoval/solver.py(241)_detect_watermark()
(Pdb) continue
Please select a method result
1. cv2.TM_CCOEFF
2. cv2.TM_CCOEFF_NORMED
3. cv2.TM_CCORR
4. cv2.TM_CCORR_NORMED
5. cv2.TM_SQDIFF
6. cv2.TM_SQDIFF_NORMED
7. CANNY_2D_FILTER
:5
2019-10-11 15:20:26 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:26 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:26 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:38 me.me.com autowatermarkremoval.utils[92544] DEBUG get_cropped_image min_x=0, min_y=0, max_x=275, max_y=105
Traceback (most recent call last):
  File "./autowatermarkremoval/solver.py", line 414, in solve
ValueError: could not broadcast input array from shape (275,105,3) into shape (105,275,3)
2019-10-11 15:20:38 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCOEFF (315, 281) (590, 386)
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCOEFF_NORMED (109, 302) (384, 407)
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCORR (425, 0) (700, 105)
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_CCORR_NORMED (179, 0) (454, 105)
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_SQDIFF (120, 325) (395, 430)
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG cv2.TM_SQDIFF_NORMED (0, 0) (275, 105)
2019-10-11 15:20:50 me.me.com autowatermarkremoval.solver[92544] DEBUG CANNY_2D_FILTER (154, 314) (429, 419)
2019-10-11 15:20:50 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:51 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:51 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:51 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:51 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:51 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
2019-10-11 15:20:51 me.me.com matplotlib.axes._base[92544] DEBUG update_title_pos
>
```

**Comment by ThanhBarTN** [comment]
@whitelok Can you please help us with this issue?

**Comment by whitelok** [comment]
please. git pull the latest code and check it fixed. And reopen it if this issue still there
