### ISSUE TITLE
Can not load watermark image

### ISSUE THREAD

**Issue by AlexRMU** [whitelok/watermark-remover#36]
`!python ./main.pyc --mode remove --watermark_path ./result/W_59_116_3.npy --alpha_path ./result/alph_59_116_3.npy --image_path ./demo/fotolia_168667147.jpg`

```
Traceback (most recent call last):
  File "./main.py", line 78, in <module>
  File "./autowatermarkremoval/remover.py", line 152, in remove
  File "./autowatermarkremoval/remover.py", line 31, in __init__
AssertionError: Can not load watermark image from result/W_59_116_3.npy
```
I only used commands from the documentation

**Comment by whitelok** [comment]
Will check this ASAP

**Comment by whitelok** [comment]
Thanks for someone's suggestion. ALL CODE IN THIS WILL BE DELETE FOREVER. So no support anymore.

Closing
