### ISSUE TITLE
Error for full-size watermark

### ISSUE THREAD

**Issue by martinschaef** [whitelok/watermark-remover#7]
Thanks for providing the python3.7 binaries.
Ran into a bug when running it on my own test data:

```
2019-01-17 18:52:32 186590ce2455.ant.amazon.com autowatermarkremoval.solver[720] DEBUG saving image tmp/step_1_Wm_gradx.jpg
2019-01-17 18:52:32 186590ce2455.ant.amazon.com autowatermarkremoval.solver[720] DEBUG saving image tmp/step_1_Wm_grady.jpg
2019-01-17 18:52:32 186590ce2455.ant.amazon.com autowatermarkremoval.solver[720] DEBUG saving image tmp/step_2_Wm_gradx_cropped.jpg
2019-01-17 18:52:32 186590ce2455.ant.amazon.com autowatermarkremoval.solver[720] DEBUG saving image tmp/step_2_Wm_gradx_cropped.jpg
Traceback (most recent call last):
  File "./main.py", line 23, in <module>
  File "./autowatermarkremoval/solver.py", line 356, in solve
  File "./autowatermarkremoval/solver.py", line 313, in solve
  File "./autowatermarkremoval/solver.py", line 209, in _possion_reconstruct
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/filter.cpp:288: error: (-215:Assertion failed) wholeSize.width > 0 && wholeSize.height > 0 in function 'proceed'
```

The issue seems to be that the watermark in my test set is an actual overlay of the whole picture, so the files step_2_Wm_gradx_cropped.jpg and step_2_Wm_grady_cropped.jpg are basically empty (if I understand the algorithm correctly). 

Happy to send you a sample set of the data if you are interested.

**Comment by whitelok** [comment]
It is very good for me to debug with your sample set. You can send it to my email whitelok@gmai.com.

**Comment by whitelok** [comment]
Hi martinschaef, I have fixed in new push. Could you help me to verify? and you can refer to https://github.com/whitelok/watermark-remover#tips-1 to remove the issue. a0cc9a8
